name: Test League Update

on:
  repository_dispatch:
    types: [league-update]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch received
        env:
            LEAGUE_JSON: ${{ github.event.client_payload.league }}
        run: |
            echo "Success!"
            echo "$LEAGUE_JSON"